function output_reactants_string = ReadingCEAMReactantsInput(input_struct_from_OPT)

output_reactants_string = '''reactants'',';
reactant_names = fieldnames(input_struct_from_OPT);
for i=1:length(reactant_names)
    output_reactants_string = strcat(output_reactants_string, ...
        '''name'',''', (reactant_names{i, 1}), ...
        ''',''wt'',', num2str(input_struct_from_OPT.(reactant_names{i, 1}).weight_percent), ',');
    element_names = fieldnames(input_struct_from_OPT.(reactant_names{i, 1}).formula);
    for j=1:length(element_names)
        output_reactants_string = strcat(output_reactants_string, ...
            '''', element_names{j, 1}, ''',', ...
            num2str(input_struct_from_OPT.(reactant_names{i, 1}).formula.(element_names{j, 1})), ',');
    end
    output_reactants_string = strcat(output_reactants_string, ...
        '''h,', input_struct_from_OPT.(reactant_names{i, 1}).enthalpy_unit, ...
        ''',', num2str(input_struct_from_OPT.(reactant_names{i, 1}).enthalpy), ',');
    if strcmp(input_struct_from_OPT.(reactant_names{i, 1}).density_unit,'g/cm^3')
        output_reactants_string = strcat(output_reactants_string, ...
            '''rho,g/cc'',', num2str(input_struct_from_OPT.(reactant_names{i, 1}).density), ',');
    else
        output_reactants_string = strcat(output_reactants_string, ...
            '''rho,', input_struct_from_OPT.(reactant_names{i, 1}).density_unit, ...
            ''',', num2str(input_struct_from_OPT.(reactant_names{i, 1}).density), ',');
    end
end

end